/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import code.newProductCode;
import code.readcsv;
import data.loadData;
import db.db;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.HashMap;
import java.util.Map;
import java.util.Collections;

/**
 *
 * @author Mr.Shamly
 */
public class product extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public product() {
        initComponents();
        setLocationRelativeTo(null); 
        show_customer();
    }

    private List<readcsv> loadedData;

    private void loadCSV() {

        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);

        if (result == fileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            loadedData = loadData.Loadcsv(selectedFile);
            //System.out.println("Size" + loadedData.size());
            displayDataInTable(loadedData);
        }
    }

    private void displayDataInTable(List<readcsv> dataList) {

        DefaultTableModel model = (DefaultTableModel) tblProduct.getModel();
        model.setRowCount(0);
        for (int i = 0; i < dataList.size(); i++) {
            readcsv row = dataList.get(i);
            model.addRow(new Object[]{
                row.getTra_id(),
                row.getC_id(),
                row.getP_id(),
                row.getP_name(),
                row.getQuantity(),
                row.getP_unit(),
                row.getDate(),
                row.getPrice(),
                row.getRegion()
            });
        }

    }

    public ArrayList<newProductCode> CustomerList() {
        ArrayList<newProductCode> CustomerList = new ArrayList<>();
        try {
            Connection con;
            Statement st;
            con = db.getConnection();
            st = con.createStatement();
            String query = "Select * from product";
            ResultSet rs = st.executeQuery(query);
            newProductCode cus;
            while (rs.next()) {
                cus = new newProductCode(rs.getInt("tra_id"), rs.getInt("c_id"), rs.getInt("p_id"), rs.getString("p_name"), rs.getInt("quantity"), rs.getDouble("p_unit"), rs.getString("date"), rs.getDouble("price"), rs.getString("region"));
                CustomerList.add(cus);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return CustomerList;
    }

    public void show_customer() {
        ArrayList<newProductCode> list = CustomerList();
        DefaultTableModel model = (DefaultTableModel) tblProduct.getModel();
        Object[] row = new Object[9];

        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getTra_id();
            row[1] = list.get(i).getC_id();
            row[2] = list.get(i).getP_id();
            row[3] = list.get(i).getP_name();
            row[4] = list.get(i).getQuantity();
            row[5] = list.get(i).getP_unit();
            row[6] = list.get(i).getDate();
            row[7] = list.get(i).getPrice();
            row[8] = list.get(i).getRegion();

            model.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        addproduct = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblProduct.setFont(new java.awt.Font("Yu Gothic Light", 0, 14)); // NOI18N
        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transaction ID", "Customer ID", "Product ID", "Product Name", "Quantity", "Price Per Unit", "Date", "Total Price", "Region"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProduct.getTableHeader().setReorderingAllowed(false);
        tblProduct.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblProductAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tblProduct);

        jPanel2.setBackground(new java.awt.Color(0, 204, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        addproduct.setBackground(new java.awt.Color(0, 204, 102));
        addproduct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addproduct.setText("Add Product");
        addproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addproductActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 204, 102));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Analyze Data");
        jButton4.setName(""); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 204, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Search Customer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Pannel");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(addproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(313, Short.MAX_VALUE))
        );

        jButton2.setBackground(new java.awt.Color(0, 204, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 204, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Load Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        loadCSV();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void saveData() {
        try {
            Connection con = db.getConnection();
            String query = "INSERT INTO product (tra_id, c_id, p_id, p_name, quantity, p_unit, date, price, region) VALUES(?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);

            DefaultTableModel model = (DefaultTableModel) tblProduct.getModel();
            for (int i = 0; i < model.getRowCount(); i++) {
                pst.setInt(1, Integer.parseInt(model.getValueAt(i, 0).toString()));
                pst.setInt(2, Integer.parseInt(model.getValueAt(i, 1).toString()));
                pst.setInt(3, Integer.parseInt(model.getValueAt(i, 2).toString()));
                pst.setString(4, model.getValueAt(i, 3).toString());
                pst.setInt(5, Integer.parseInt(model.getValueAt(i, 4).toString()));
                pst.setDouble(6, Double.parseDouble(model.getValueAt(i, 5).toString()));
                pst.setString(7, model.getValueAt(i, 6).toString());
                pst.setDouble(8, Double.parseDouble(model.getValueAt(i, 7).toString()));
                pst.setString(9, model.getValueAt(i, 8).toString());
                pst.addBatch();
            }
            pst.executeBatch();
            JOptionPane.showMessageDialog(null, "Data saved successfully!");
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        saveData();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblProduct.getModel();

        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No data to analyze!");
            return;
        }

        Map<String, Integer> quantityMap = new HashMap<>();
        Map<String, Double> revenueMap = new HashMap<>();
        Map<String, Double> regionSalesMap = new HashMap<>();
        double totalSales = 0;

        for (int i = 0; i < model.getRowCount(); i++) {
            String productName = model.getValueAt(i, 3).toString();
            int quantity = Integer.parseInt(model.getValueAt(i, 4).toString());
            double totalPrice = Double.parseDouble(model.getValueAt(i, 7).toString());
            String region = model.getValueAt(i, 8).toString();

            totalSales += totalPrice;

            quantityMap.put(productName, quantityMap.getOrDefault(productName, 0) + quantity);
            revenueMap.put(productName, revenueMap.getOrDefault(productName, 0.0) + totalPrice);
            regionSalesMap.put(region, regionSalesMap.getOrDefault(region, 0.0) + totalPrice);
        }

        String bestSellingProduct = Collections.max(quantityMap.entrySet(), Map.Entry.comparingByValue()).getKey();
        String topRevenueProduct = Collections.max(revenueMap.entrySet(), Map.Entry.comparingByValue()).getKey();

// Build HTML table for region sales
        StringBuilder regionTable = new StringBuilder();
        regionTable.append("<table border='1' cellpadding='8' cellspacing='1'>")
                .append("<tr><th>Region</th><th>Sales (Rs.)</th></tr>");
        for (Map.Entry<String, Double> entry : regionSalesMap.entrySet()) {
            regionTable.append("<tr>")
                    .append("<td>").append(entry.getKey()).append("</td>")
                    .append("<td>").append(String.format("%.2f", entry.getValue())).append("</td>")
                    .append("</tr>");
        }
        regionTable.append("</table>");

// Final HTML message
        String message = "<html>"
                + "<h2 style='text-align:center;'>Sales Analysis</h2>"
                + "<table cellpadding='5' cellspacing='0'>"
                + "<tr><td><b>Total Sales:</b></td><td>Rs. " + String.format("%.2f", totalSales) + "</td></tr>"
                + "<tr><td><b>Best-Selling Product (Quantity):</b></td><td>" + bestSellingProduct + "</td></tr>"
                + "<tr><td><b>Top Revenue Product:</b></td><td>" + topRevenueProduct + "</td></tr>"
                + "</table><br>"
                + "<b>Sales by Region:</b><br>"
                + regionTable.toString()
                + "</html>";

        JOptionPane.showMessageDialog(this, message, "Sales Analysis", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void addproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addproductActionPerformed
        // TODO add your handling code here:
        addproduct addproductForm = new addproduct();
        addproductForm.setVisible(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_addproductActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        customer customerForm = new customer();
        customerForm.setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void tblProductAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblProductAncestorAdded
        // TODO add your handling code here:
        // Header – Dark Green
        tblProduct.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
        tblProduct.getTableHeader().setBackground(new java.awt.Color(0, 128, 0));  // Dark Green
        tblProduct.getTableHeader().setForeground(java.awt.Color.black);

        // Row Height
        tblProduct.setRowHeight(30);

        // Grid lines – Soft Green
        tblProduct.setShowGrid(true);
        tblProduct.setGridColor(new java.awt.Color(0, 180, 0)); // Light Green

        // Table Font
        tblProduct.setFont(new java.awt.Font("Segoe UI", 0, 14));

        // Background color of table (light green)
        tblProduct.setBackground(new java.awt.Color(230, 255, 230));

        // Zebra Rows (shades of green)
        tblProduct.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(
                    javax.swing.JTable table, Object value,
                    boolean isSelected, boolean hasFocus,
                    int row, int column) {

                java.awt.Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                if (!isSelected) {
                    if (row % 2 == 0) {
                        c.setBackground(new java.awt.Color(220, 255, 220)); // light green
                    } else {
                        c.setBackground(new java.awt.Color(240, 255, 240)); // lighter green
                    }
                    c.setForeground(java.awt.Color.BLACK);
                } else {
                    c.setBackground(new java.awt.Color(0, 150, 0)); // selected row green
                    c.setForeground(java.awt.Color.WHITE);
                }

                return c;
            }
        });
    }//GEN-LAST:event_tblProductAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addproduct;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProduct;
    // End of variables declaration//GEN-END:variables
}
